export const editorTheme = {
  ltr: 'text-left',
  rtl: 'text-right',
  placeholder: 'text-muted-foreground/60 select-none pointer-events-none absolute top-3.5 left-4 text-sm font-normal leading-relaxed',
  paragraph: 'mb-3 leading-relaxed text-foreground text-sm font-normal last:mb-0',
  quote: 'border-l-4 border-primary/70 bg-muted/40 pl-4 py-2 my-3 italic text-muted-foreground rounded-r-md text-sm',
  heading: {
    h1: 'text-2xl font-bold tracking-tight text-foreground mt-6 mb-3 first:mt-1',
    h2: 'text-xl font-semibold tracking-tight text-foreground mt-5 mb-2.5 first:mt-1',
    h3: 'text-base font-semibold tracking-tight text-foreground mt-4 mb-2 first:mt-1',
    h4: 'text-sm font-semibold tracking-tight text-foreground mt-3 mb-1.5 first:mt-1',
    h5: 'text-xs font-semibold tracking-tight text-foreground mt-2 mb-1 first:mt-1',
  },
  list: {
    nested: {
      listitem: 'list-none pl-3',
    },
    ol: 'list-decimal list-outside pl-6 space-y-1 my-3 text-sm text-foreground',
    ul: 'list-disc list-outside pl-6 space-y-1 my-3 text-sm text-foreground',
    listitem: 'leading-relaxed pl-1',
    listitemChecked: 'line-through text-muted-foreground transition-all duration-150',
    listitemUnchecked: 'text-foreground',
  },
  link: 'text-primary underline underline-offset-4 font-medium hover:text-primary/80 transition-colors cursor-pointer inline-flex items-center gap-0.5',
  text: {
    bold: 'font-bold text-foreground',
    italic: 'italic',
    underline: 'underline underline-offset-4 decoration-current/60',
    strikethrough: 'line-through opacity-75',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-muted/80 text-foreground font-mono text-[12px] px-1.5 py-0.5 rounded border border-border/80 font-medium',
    subscript: 'align-sub text-[10px] leading-none',
    superscript: 'align-super text-[10px] leading-none',
  },
  code: 'bg-muted/60 text-foreground font-mono text-xs p-3.5 my-3 rounded-lg border border-border/70 overflow-x-auto block leading-relaxed',
  table: 'border-collapse w-full my-4 border border-border text-xs rounded-xl overflow-hidden shadow-2xs',
  tableRow: 'hover:bg-muted/20 transition-colors border-b border-border/70',
  tableCell: 'border border-border/80 p-2.5 min-w-[70px] align-top text-xs relative text-foreground',
  tableCellHeader: 'border border-border/80 bg-muted/60 p-2.5 min-w-[70px] align-top text-xs font-semibold text-foreground text-left',
  tableCellSelected: 'bg-primary/10 ring-1 ring-primary inset-0',
  codeHighlight: {
    atrule: 'text-indigo-600 dark:text-indigo-400',
    attr: 'text-sky-600 dark:text-sky-400',
    boolean: 'text-rose-600 dark:text-rose-400 font-semibold',
    builtin: 'text-emerald-600 dark:text-emerald-400',
    cdata: 'text-muted-foreground italic',
    char: 'text-amber-600 dark:text-amber-400',
    class: 'text-purple-600 dark:text-purple-400 font-semibold',
    'class-name': 'text-purple-600 dark:text-purple-400 font-semibold',
    comment: 'text-muted-foreground italic',
    constant: 'text-orange-600 dark:text-orange-400',
    deleted: 'text-destructive',
    doctype: 'text-muted-foreground',
    entity: 'text-amber-600 dark:text-amber-400',
    function: 'text-blue-600 dark:text-blue-400 font-medium',
    important: 'text-rose-600 dark:text-rose-400 font-bold',
    inserted: 'text-emerald-600 dark:text-emerald-400',
    keyword: 'text-indigo-600 dark:text-indigo-400 font-semibold',
    number: 'text-amber-600 dark:text-amber-400',
    operator: 'text-muted-foreground',
    prolog: 'text-muted-foreground',
    property: 'text-sky-600 dark:text-sky-400',
    punctuation: 'text-muted-foreground/80',
    regex: 'text-rose-600 dark:text-rose-400',
    selector: 'text-emerald-600 dark:text-emerald-400',
    string: 'text-emerald-600 dark:text-emerald-400',
    symbol: 'text-amber-600 dark:text-amber-400',
    tag: 'text-rose-600 dark:text-rose-400',
    url: 'text-primary underline',
    variable: 'text-foreground',
  },
  hr: 'my-5 border-t border-border/80',
};
