import {
  Heart,
  Sparkles,
  Users2,
  CalendarDays,
  GraduationCap,
  Gift,
  Cake,
  Award,
  UtensilsCrossed,
  Music,
  Camera,
  Mic2,
  Sliders,
  Armchair,
  LayoutGrid,
  Trees,
  Glasses,
} from 'lucide-react';
import { EventTypeOption, SeatingOption, CateringOption, ServiceOption, WizardFormData } from './types';

export const INITIAL_WIZARD_DATA: WizardFormData = {
  eventType: 'wedding',
  eventName: '',
  eventDate: new Date(Date.now() + 14 * 86400000), // 2 weeks from now
  timeSlot: 'evening',
  guestCount: 150,
  seatingLayout: 'banquet',
  cateringType: 'deluxe',
  dietaryRequirements: ['halal'],
  addons: ['photography', 'sound'],
  organizerName: '',
  contactEmail: '',
  contactPhone: '',
  companyName: '',
  specialNotes: '',
  agreeTerms: false,
};

export const EVENT_TYPE_OPTIONS: EventTypeOption[] = [
  {
    id: 'engagement',
    nameKey: 'wizard.events.engagement',
    defaultName: 'Engagement',
    descKey: 'wizard.events.engagementDesc',
    defaultDesc: 'Intimate celebration for couples and family',
    icon: Sparkles,
    category: 'social',
  },
  {
    id: 'henna-night',
    nameKey: 'wizard.events.hennaNight',
    defaultName: 'Henna Night',
    descKey: 'wizard.events.hennaNightDesc',
    defaultDesc: 'Traditional pre-wedding bridal evening with vibrant decor',
    icon: Sparkles,
    category: 'social',
  },
  {
    id: 'wedding',
    nameKey: 'wizard.events.wedding',
    defaultName: 'Wedding',
    descKey: 'wizard.events.weddingDesc',
    defaultDesc: 'Grand ceremony and reception celebration',
    icon: Heart,
    badge: 'Popular',
    category: 'social',
  },
  {
    id: 'corporate-event',
    nameKey: 'wizard.events.corporate',
    defaultName: 'Corporate Event',
    descKey: 'wizard.events.corporateDesc',
    defaultDesc: 'Conferences, gala dinners, annual meetings, and team celebrations',
    icon: CalendarDays,
    category: 'corporate',
  },
  {
    id: 'prom',
    nameKey: 'wizard.events.prom',
    defaultName: 'Prom',
    descKey: 'wizard.events.promDesc',
    defaultDesc: 'Graduation ball, formal school dances & celebrations',
    icon: GraduationCap,
    category: 'social',
  },
  {
    id: 'christmas-party',
    nameKey: 'wizard.events.christmasParty',
    defaultName: 'Christmas Party',
    descKey: 'wizard.events.christmasPartyDesc',
    defaultDesc: 'Festive holiday gathering with themed dinner and music',
    icon: Gift,
    category: 'family',
  },
  {
    id: 'birthday',
    nameKey: 'wizard.events.birthday',
    defaultName: 'Birthday & Anniversary',
    descKey: 'wizard.events.birthdayDesc',
    defaultDesc: 'Milestone birthdays, sweet seventeen & golden anniversaries',
    icon: Cake,
    category: 'family',
  },
  {
    id: 'gala-dinner',
    nameKey: 'wizard.events.galaDinner',
    defaultName: 'Gala & Charity Dinner',
    descKey: 'wizard.events.galaDinnerDesc',
    defaultDesc: 'High-profile charity fundraisers and awards evenings',
    icon: Award,
    category: 'corporate',
  },
];

export const SEATING_LAYOUTS: SeatingOption[] = [
  {
    id: 'banquet',
    nameKey: 'wizard.seating.banquet',
    defaultName: 'Banquet Round Tables',
    capacity: '8-10 pax/table',
    icon: Armchair,
  },
  {
    id: 'cocktail',
    nameKey: 'wizard.seating.cocktail',
    defaultName: 'Cocktail & Standing Lounge',
    capacity: 'Fluid social flow',
    icon: Glasses,
  },
  {
    id: 'classroom',
    nameKey: 'wizard.seating.classroom',
    defaultName: 'Classroom / Theater',
    capacity: 'Optimal presentation view',
    icon: LayoutGrid,
  },
  {
    id: 'outdoor',
    nameKey: 'wizard.seating.outdoor',
    defaultName: 'Outdoor Garden Pavilion',
    capacity: 'Open-air scenic setup',
    icon: Trees,
  },
];

export const CATERING_PACKAGES: CateringOption[] = [
  {
    id: 'standard',
    nameKey: 'wizard.catering.standard',
    defaultName: 'Standard Buffet',
    pricePerPax: 150000,
    descriptionKey: 'wizard.catering.standardDesc',
    defaultDescription: '5 main courses, 2 appetizers, seasonal fruits, iced tea & mineral water',
  },
  {
    id: 'deluxe',
    nameKey: 'wizard.catering.deluxe',
    defaultName: 'Deluxe Grand Buffet',
    pricePerPax: 275000,
    descriptionKey: 'wizard.catering.deluxeDesc',
    defaultDescription: '8 main courses, 4 food stalls, premium dessert bar, signature mocktails',
    popular: true,
  },
  {
    id: 'plated',
    nameKey: 'wizard.catering.plated',
    defaultName: 'Royal 4-Course Plated',
    pricePerPax: 450000,
    descriptionKey: 'wizard.catering.platedDesc',
    defaultDescription: 'Fine dining service with personalized chef plating and curated beverage pairings',
  },
  {
    id: 'canapes',
    nameKey: 'wizard.catering.canapes',
    defaultName: 'Canapes & Hors d\'oeuvres',
    pricePerPax: 180000,
    descriptionKey: 'wizard.catering.canapesDesc',
    defaultDescription: '12 bite-sized gourmet savory & sweet items passed continuously by servers',
  },
];

export const ADDON_SERVICES: ServiceOption[] = [
  {
    id: 'photography',
    nameKey: 'wizard.services.photography',
    defaultName: 'Photography & Cinematic Video',
    price: 8500000,
    icon: Camera,
  },
  {
    id: 'sound',
    nameKey: 'wizard.services.sound',
    defaultName: 'Concert Sound System & Lighting',
    price: 6000000,
    icon: Sliders,
  },
  {
    id: 'music',
    nameKey: 'wizard.services.music',
    defaultName: 'Live Acoustic Band (4-Piece)',
    price: 5000000,
    icon: Music,
  },
  {
    id: 'mc',
    nameKey: 'wizard.services.mc',
    defaultName: 'Bilingual Master of Ceremony',
    price: 3500000,
    icon: Mic2,
  },
];
